# Generated by Django 4.0.4 on 2022-04-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.FileField(upload_to='books/static/books/images'),
        ),
    ]
